<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTDWzpU6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTDWzpU6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTDWzpU6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTDWzpU6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTDWzpU6\App_KernelDevDebugContainer([
    'container.build_hash' => 'TDWzpU6',
    'container.build_id' => 'f02043bf',
    'container.build_time' => 1670233625,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTDWzpU6');
