<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'aboutPage' => [[], ['_controller' => 'App\\Controller\\aboutController::aboutPage'], [], [['text', '/about']], [], [], []],
    'accountPage' => [[], ['_controller' => 'App\\Controller\\accountController::accountPage'], [], [['text', '/account']], [], [], []],
    'cartPage' => [[], ['_controller' => 'App\\Controller\\cartController::cartPage'], [], [['text', '/cart']], [], [], []],
    'contactPage' => [[], ['_controller' => 'App\\Controller\\contactController::contactPage'], [], [['text', '/contact']], [], [], []],
    'createPage' => [[], ['_controller' => 'App\\Controller\\createController::createPage'], [], [['text', '/create']], [], [], []],
    'product_get' => [[], ['_controller' => 'App\\Controller\\createController::getNumber'], [], [['text', '/get']], [], [], []],
    'mainPage' => [[], ['_controller' => 'App\\Controller\\myController::mainPage'], [], [['text', '/']], [], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\myController::loginAction'], [], [['text', '/login']], [], [], []],
    'productPage' => [[], ['_controller' => 'App\\Controller\\productController::productPage'], [], [['text', '/product']], [], [], []],
    'productId' => [['productId'], ['_controller' => 'App\\Controller\\productController::productId'], [], [['variable', '/', '[^/]++', 'productId', true], ['text', '/product']], [], [], []],
    'registrationPage' => [[], ['_controller' => 'App\\Controller\\registrationController::registrationPage'], [], [['text', '/registration']], [], [], []],
    'registrationEdit' => [['userId'], ['_controller' => 'App\\Controller\\registrationController::registrationEdit'], [], [['variable', '/', '[^/]++', 'userId', true], ['text', '/registration/edit']], [], [], []],
    'logout' => [[], [], [], [['text', '/logout']], [], [], []],
];
